using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace Villsource.CodeGen
{
    [Generator]
    public class EntityBoilerplateGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax c &&
                                                c.Modifiers.Any(SyntaxKind.PartialKeyword) && c.BaseList != null,
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(spc, source!));
        }

        private static EntityInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = ModelExtensions.GetDeclaredSymbol(context.SemanticModel, classDeclaration) as INamedTypeSymbol;

            if (symbol == null) return null;

            bool isAuditable = symbol.Interfaces.Any(i => i.Name == "IAuditableEntity");
            bool isSoftDeletable = symbol.Interfaces.Any(i => i.Name == "ISoftDeletable");

            if (!isAuditable && !isSoftDeletable) return null;

            return new EntityInfo
            {
                Name = symbol.Name,
                Namespace =
                    symbol.ContainingNamespace.IsGlobalNamespace
                        ? string.Empty
                        : symbol.ContainingNamespace.ToString(),
                IsPublic = symbol.DeclaredAccessibility == Accessibility.Public,
                IsSealed = symbol.IsSealed,
                IsAuditable = isAuditable,
                IsSoftDeletable = isSoftDeletable
            };
        }

        private static void Execute(SourceProductionContext context, EntityInfo entityInfo)
        {
            var accessModifier = entityInfo.IsPublic ? "public" : "internal";
            var sealedModifier = entityInfo.IsSealed ? " sealed" : "";
            var namespaceDeclaration = string.IsNullOrEmpty(entityInfo.Namespace)
                ? ""
                : $"namespace {entityInfo.Namespace};";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine(namespaceDeclaration);
            sb.AppendLine();

            sb.AppendLine($"{accessModifier}{sealedModifier} partial class {entityInfo.Name}");
            sb.AppendLine("{");

            if (entityInfo.IsAuditable)
            {
                sb.AppendLine("    public DateTimeOffset CreatedOnUtc { get; private set; }");
                sb.AppendLine("    public string? CreatedBy { get; private set; }");
                sb.AppendLine("    public DateTimeOffset? LastModifiedOnUtc { get; private set; }");
                sb.AppendLine("    public string? LastModifiedBy { get; private set; }");
            }

            if (entityInfo.IsSoftDeletable)
            {
                sb.AppendLine("    public bool IsDeleted { get; private set; }");
                sb.AppendLine("    public DateTimeOffset? DeletedOnUtc { get; private set; }");
                sb.AppendLine("    public string? DeletedBy { get; private set; }");
            }

            sb.AppendLine("}");

            context.AddSource($"{entityInfo.Name}_AuditFields.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    internal sealed record EntityInfo
    {
        public string Name { get; set; } = string.Empty;
        public string Namespace { get; set; } = string.Empty;
        public bool IsPublic { get; set; }
        public bool IsSealed { get; set; }
        public bool IsAuditable { get; set; }
        public bool IsSoftDeletable { get; set; }
    }
}