<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj"/>
        <ProjectReference Include="..\..\Core\Villsource.Tool.UniqueKey\Villsource.Tool.UniqueKey.csproj"/>
        <ProjectReference Include="..\Villsource.Modules.Oidc.Contracts\Villsource.Modules.Oidc.Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Villsource.CodeGen\Villsource.CodeGen.csproj"
                          OutputItemType="Analyzer"
                          PrivateAssets="all"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
