<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Eventing\Eventing.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
      <ProjectReference Include="..\..\Core\Villsource.Tool.UniqueKey\Villsource.Tool.UniqueKey.csproj" />
      <ProjectReference Include="..\Villsource.Modules.Elsa.Contracts\Villsource.Modules.Elsa.Contracts.csproj" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\Core\Villsource.CodeGen\Villsource.CodeGen.csproj"
                          OutputItemType="Analyzer"
                          PrivateAssets="all"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Elsa" />
      <PackageReference Include="Elsa.Persistence.EFCore.PostgreSql" />
      <PackageReference Include="Elsa.Scheduling" />
      <PackageReference Include="Elsa.Tenants" />
      <PackageReference Include="Elsa.Workflows.Api" Condition="'$(Configuration)' == 'Debug'" />
    </ItemGroup>

</Project>
